spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hotnerds
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 7047208c7b5a97ce9afd6f567c209fdf
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            clientAuthenticationMethod: CLIENT_SECRET_POST
            authorizationGrantType: authorization_code
            scope: profile_nickname, account_email
            clientName: Kakao
            #client-secret: garam
        provider:
          Kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
    jwt:
      token: #임시 최소 32자.
        secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        expire-length: 3600000
server:
  port: 8080