spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hotnerds
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  social:
    kakao:
      client_id: 7047208c7b5a97ce9afd6f567c209fdf
      redirect-uri: /social/login/kakao
      scope: profile_nickname, account_email
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https:kapi.kakao.com/v2/user/me
    url:
      base: http://localhost:8080
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7047208c7b5a97ce9afd6f567c209fdf
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-authentication-method: CLIENT_SECRET_POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
            client-secret: garam
        provider:
          Kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id